/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as OnboardingStep5RouteImport } from './routes/onboarding/step5'
import { Route as OnboardingStep4RouteImport } from './routes/onboarding/step4'
import { Route as OnboardingStep3RouteImport } from './routes/onboarding/step3'
import { Route as OnboardingStep2RouteImport } from './routes/onboarding/step2'
import { Route as OnboardingStep1RouteImport } from './routes/onboarding/step1'
import { Route as OnboardingCompleteRouteImport } from './routes/onboarding/complete'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedBrowseRouteImport } from './routes/_authenticated/_browse'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedBrowseIndexRouteImport } from './routes/_authenticated/_browse/index'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated/settings/users'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedPhotoIdRouteImport } from './routes/_authenticated/photo/$id'
import { Route as AuthenticatedBrowseMapRouteImport } from './routes/_authenticated/_browse/map'
import { Route as AuthenticatedSettingsLibrariesIndexRouteImport } from './routes/_authenticated/settings/libraries/index'
import { Route as AuthenticatedBrowseAlbumsIndexRouteImport } from './routes/_authenticated/_browse/albums/index'
import { Route as AuthenticatedSettingsLibrariesLibraryIdRouteImport } from './routes/_authenticated/settings/libraries/$libraryId'
import { Route as AuthenticatedBrowseAlbumsAlbumIdRouteImport } from './routes/_authenticated/_browse/albums/$albumId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingStep5Route = OnboardingStep5RouteImport.update({
  id: '/step5',
  path: '/step5',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingStep4Route = OnboardingStep4RouteImport.update({
  id: '/step4',
  path: '/step4',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingStep3Route = OnboardingStep3RouteImport.update({
  id: '/step3',
  path: '/step3',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingStep2Route = OnboardingStep2RouteImport.update({
  id: '/step2',
  path: '/step2',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingStep1Route = OnboardingStep1RouteImport.update({
  id: '/step1',
  path: '/step1',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingCompleteRoute = OnboardingCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => OnboardingRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBrowseRoute = AuthenticatedBrowseRouteImport.update({
  id: '/_browse',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedBrowseIndexRoute =
  AuthenticatedBrowseIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBrowseRoute,
  } as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedPhotoIdRoute = AuthenticatedPhotoIdRouteImport.update({
  id: '/photo/$id',
  path: '/photo/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBrowseMapRoute = AuthenticatedBrowseMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedBrowseRoute,
} as any)
const AuthenticatedSettingsLibrariesIndexRoute =
  AuthenticatedSettingsLibrariesIndexRouteImport.update({
    id: '/libraries/',
    path: '/libraries/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedBrowseAlbumsIndexRoute =
  AuthenticatedBrowseAlbumsIndexRouteImport.update({
    id: '/albums/',
    path: '/albums/',
    getParentRoute: () => AuthenticatedBrowseRoute,
  } as any)
const AuthenticatedSettingsLibrariesLibraryIdRoute =
  AuthenticatedSettingsLibrariesLibraryIdRouteImport.update({
    id: '/libraries/$libraryId',
    path: '/libraries/$libraryId',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedBrowseAlbumsAlbumIdRoute =
  AuthenticatedBrowseAlbumsAlbumIdRouteImport.update({
    id: '/albums/$albumId',
    path: '/albums/$albumId',
    getParentRoute: () => AuthenticatedBrowseRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedBrowseIndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/step1': typeof OnboardingStep1Route
  '/onboarding/step2': typeof OnboardingStep2Route
  '/onboarding/step3': typeof OnboardingStep3Route
  '/onboarding/step4': typeof OnboardingStep4Route
  '/onboarding/step5': typeof OnboardingStep5Route
  '/onboarding/': typeof OnboardingIndexRoute
  '/map': typeof AuthenticatedBrowseMapRoute
  '/photo/$id': typeof AuthenticatedPhotoIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/albums/$albumId': typeof AuthenticatedBrowseAlbumsAlbumIdRoute
  '/settings/libraries/$libraryId': typeof AuthenticatedSettingsLibrariesLibraryIdRoute
  '/albums/': typeof AuthenticatedBrowseAlbumsIndexRoute
  '/settings/libraries/': typeof AuthenticatedSettingsLibrariesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedBrowseIndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/invite/$token': typeof InviteTokenRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/step1': typeof OnboardingStep1Route
  '/onboarding/step2': typeof OnboardingStep2Route
  '/onboarding/step3': typeof OnboardingStep3Route
  '/onboarding/step4': typeof OnboardingStep4Route
  '/onboarding/step5': typeof OnboardingStep5Route
  '/onboarding': typeof OnboardingIndexRoute
  '/map': typeof AuthenticatedBrowseMapRoute
  '/photo/$id': typeof AuthenticatedPhotoIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/albums/$albumId': typeof AuthenticatedBrowseAlbumsAlbumIdRoute
  '/settings/libraries/$libraryId': typeof AuthenticatedSettingsLibrariesLibraryIdRoute
  '/albums': typeof AuthenticatedBrowseAlbumsIndexRoute
  '/settings/libraries': typeof AuthenticatedSettingsLibrariesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/_authenticated/_browse': typeof AuthenticatedBrowseRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/step1': typeof OnboardingStep1Route
  '/onboarding/step2': typeof OnboardingStep2Route
  '/onboarding/step3': typeof OnboardingStep3Route
  '/onboarding/step4': typeof OnboardingStep4Route
  '/onboarding/step5': typeof OnboardingStep5Route
  '/onboarding/': typeof OnboardingIndexRoute
  '/_authenticated/_browse/map': typeof AuthenticatedBrowseMapRoute
  '/_authenticated/photo/$id': typeof AuthenticatedPhotoIdRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/_authenticated/_browse/': typeof AuthenticatedBrowseIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/_browse/albums/$albumId': typeof AuthenticatedBrowseAlbumsAlbumIdRoute
  '/_authenticated/settings/libraries/$libraryId': typeof AuthenticatedSettingsLibrariesLibraryIdRoute
  '/_authenticated/_browse/albums/': typeof AuthenticatedBrowseAlbumsIndexRoute
  '/_authenticated/settings/libraries/': typeof AuthenticatedSettingsLibrariesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/onboarding'
    | '/settings'
    | '/invite/$token'
    | '/onboarding/complete'
    | '/onboarding/step1'
    | '/onboarding/step2'
    | '/onboarding/step3'
    | '/onboarding/step4'
    | '/onboarding/step5'
    | '/onboarding/'
    | '/map'
    | '/photo/$id'
    | '/settings/account'
    | '/settings/users'
    | '/settings/'
    | '/albums/$albumId'
    | '/settings/libraries/$libraryId'
    | '/albums/'
    | '/settings/libraries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/invite/$token'
    | '/onboarding/complete'
    | '/onboarding/step1'
    | '/onboarding/step2'
    | '/onboarding/step3'
    | '/onboarding/step4'
    | '/onboarding/step5'
    | '/onboarding'
    | '/map'
    | '/photo/$id'
    | '/settings/account'
    | '/settings/users'
    | '/settings'
    | '/albums/$albumId'
    | '/settings/libraries/$libraryId'
    | '/albums'
    | '/settings/libraries'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/logout'
    | '/onboarding'
    | '/_authenticated/_browse'
    | '/_authenticated/settings'
    | '/invite/$token'
    | '/onboarding/complete'
    | '/onboarding/step1'
    | '/onboarding/step2'
    | '/onboarding/step3'
    | '/onboarding/step4'
    | '/onboarding/step5'
    | '/onboarding/'
    | '/_authenticated/_browse/map'
    | '/_authenticated/photo/$id'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/users'
    | '/_authenticated/_browse/'
    | '/_authenticated/settings/'
    | '/_authenticated/_browse/albums/$albumId'
    | '/_authenticated/settings/libraries/$libraryId'
    | '/_authenticated/_browse/albums/'
    | '/_authenticated/settings/libraries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/step5': {
      id: '/onboarding/step5'
      path: '/step5'
      fullPath: '/onboarding/step5'
      preLoaderRoute: typeof OnboardingStep5RouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/step4': {
      id: '/onboarding/step4'
      path: '/step4'
      fullPath: '/onboarding/step4'
      preLoaderRoute: typeof OnboardingStep4RouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/step3': {
      id: '/onboarding/step3'
      path: '/step3'
      fullPath: '/onboarding/step3'
      preLoaderRoute: typeof OnboardingStep3RouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/step2': {
      id: '/onboarding/step2'
      path: '/step2'
      fullPath: '/onboarding/step2'
      preLoaderRoute: typeof OnboardingStep2RouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/step1': {
      id: '/onboarding/step1'
      path: '/step1'
      fullPath: '/onboarding/step1'
      preLoaderRoute: typeof OnboardingStep1RouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/complete': {
      id: '/onboarding/complete'
      path: '/complete'
      fullPath: '/onboarding/complete'
      preLoaderRoute: typeof OnboardingCompleteRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_browse': {
      id: '/_authenticated/_browse'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedBrowseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/_browse/': {
      id: '/_authenticated/_browse/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedBrowseIndexRouteImport
      parentRoute: typeof AuthenticatedBrowseRoute
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/photo/$id': {
      id: '/_authenticated/photo/$id'
      path: '/photo/$id'
      fullPath: '/photo/$id'
      preLoaderRoute: typeof AuthenticatedPhotoIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_browse/map': {
      id: '/_authenticated/_browse/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedBrowseMapRouteImport
      parentRoute: typeof AuthenticatedBrowseRoute
    }
    '/_authenticated/settings/libraries/': {
      id: '/_authenticated/settings/libraries/'
      path: '/libraries'
      fullPath: '/settings/libraries/'
      preLoaderRoute: typeof AuthenticatedSettingsLibrariesIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/_browse/albums/': {
      id: '/_authenticated/_browse/albums/'
      path: '/albums'
      fullPath: '/albums/'
      preLoaderRoute: typeof AuthenticatedBrowseAlbumsIndexRouteImport
      parentRoute: typeof AuthenticatedBrowseRoute
    }
    '/_authenticated/settings/libraries/$libraryId': {
      id: '/_authenticated/settings/libraries/$libraryId'
      path: '/libraries/$libraryId'
      fullPath: '/settings/libraries/$libraryId'
      preLoaderRoute: typeof AuthenticatedSettingsLibrariesLibraryIdRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/_browse/albums/$albumId': {
      id: '/_authenticated/_browse/albums/$albumId'
      path: '/albums/$albumId'
      fullPath: '/albums/$albumId'
      preLoaderRoute: typeof AuthenticatedBrowseAlbumsAlbumIdRouteImport
      parentRoute: typeof AuthenticatedBrowseRoute
    }
  }
}

interface AuthenticatedBrowseRouteChildren {
  AuthenticatedBrowseMapRoute: typeof AuthenticatedBrowseMapRoute
  AuthenticatedBrowseIndexRoute: typeof AuthenticatedBrowseIndexRoute
  AuthenticatedBrowseAlbumsAlbumIdRoute: typeof AuthenticatedBrowseAlbumsAlbumIdRoute
  AuthenticatedBrowseAlbumsIndexRoute: typeof AuthenticatedBrowseAlbumsIndexRoute
}

const AuthenticatedBrowseRouteChildren: AuthenticatedBrowseRouteChildren = {
  AuthenticatedBrowseMapRoute: AuthenticatedBrowseMapRoute,
  AuthenticatedBrowseIndexRoute: AuthenticatedBrowseIndexRoute,
  AuthenticatedBrowseAlbumsAlbumIdRoute: AuthenticatedBrowseAlbumsAlbumIdRoute,
  AuthenticatedBrowseAlbumsIndexRoute: AuthenticatedBrowseAlbumsIndexRoute,
}

const AuthenticatedBrowseRouteWithChildren =
  AuthenticatedBrowseRoute._addFileChildren(AuthenticatedBrowseRouteChildren)

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedSettingsLibrariesLibraryIdRoute: typeof AuthenticatedSettingsLibrariesLibraryIdRoute
  AuthenticatedSettingsLibrariesIndexRoute: typeof AuthenticatedSettingsLibrariesIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
  AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedSettingsLibrariesLibraryIdRoute:
    AuthenticatedSettingsLibrariesLibraryIdRoute,
  AuthenticatedSettingsLibrariesIndexRoute:
    AuthenticatedSettingsLibrariesIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedBrowseRoute: typeof AuthenticatedBrowseRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedPhotoIdRoute: typeof AuthenticatedPhotoIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBrowseRoute: AuthenticatedBrowseRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedPhotoIdRoute: AuthenticatedPhotoIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface OnboardingRouteChildren {
  OnboardingCompleteRoute: typeof OnboardingCompleteRoute
  OnboardingStep1Route: typeof OnboardingStep1Route
  OnboardingStep2Route: typeof OnboardingStep2Route
  OnboardingStep3Route: typeof OnboardingStep3Route
  OnboardingStep4Route: typeof OnboardingStep4Route
  OnboardingStep5Route: typeof OnboardingStep5Route
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingCompleteRoute: OnboardingCompleteRoute,
  OnboardingStep1Route: OnboardingStep1Route,
  OnboardingStep2Route: OnboardingStep2Route,
  OnboardingStep3Route: OnboardingStep3Route,
  OnboardingStep4Route: OnboardingStep4Route,
  OnboardingStep5Route: OnboardingStep5Route,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
