# Generated by Django 6.0.4 on 2026-07-19 20:08

from django.db import migrations, models


def backfill_site_admin(apps, schema_editor):
    # The settings area's Users page is gated on is_staff, which nothing set
    # before now. Existing instances are effectively single-primary-user (the
    # environment query already assumes this), so promote the earliest active
    # user to site admin. Further admins can be granted via Django admin or
    # `manage.py shell`.
    User = apps.get_model('accounts', 'User')
    if not User.objects.filter(is_staff=True).exists():
        first_user = User.objects.filter(is_active=True).order_by('date_joined').first()
        if first_user:
            first_user.is_staff = True
            first_user.save(update_fields=['is_staff'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220312_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_updated_at',
            field=models.DateTimeField(blank=True, help_text='When the avatar image was last uploaded (null means no avatar)', null=True),
        ),
        migrations.RunPython(backfill_site_admin, migrations.RunPython.noop),
    ]
